<?php

/**
 * Propriedades das variáveis:
 * Nome     => ex: $nome, $num...
 * Tipo     => ex: string, int, char, double, boolean...
 * Tamanho  => Espaço ocupado na memória
 * Valor    => ex: 10, "texto", true, 10.5...
 */